version: '3'

services:
  apprun:
    container_name: apprun
    build:
      context: .
    environment:
      - PORT=8080
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - 80:80
        - 443:443
        - 8080:8080
